CREATE TABLE "STUDENT" (
"LAST_NAME" VARCHAR(30),
"FIRST_NAME" VARCHAR(20),
"PSU_ID" VARCHAR(20) not null primary key,
"TEAM" INTEGER
);
INSERT INTO STUDENT VALUES ('BAKER','AUSTIN','ARB5671', 3);
INSERT INTO STUDENT VALUES ('BALOS','AMANDA','AZB199', 1);
INSERT INTO STUDENT VALUES ('BALTA','TRENT','TMB5577', 12);
INSERT INTO STUDENT VALUES ('CAMPBELL','MATTHEW','MRC5372', 10);
INSERT INTO STUDENT VALUES ('DUONG','CHARLIE','CTD5100', 9);
INSERT INTO STUDENT VALUES ('GOGA','DANIEL','DRG5190', 11);
INSERT INTO STUDENT VALUES ('HANKEWYCZ','ANDREW','AZH5442', 7);
INSERT INTO STUDENT VALUES ('HANSEN','ROBERT','RAH5360', 8);
INSERT INTO STUDENT VALUES ('IVANCO','JUSTIN','JJI5019', 10);
INSERT INTO STUDENT VALUES ('JACOBS','TYLER','TAJ5130', 7);
INSERT INTO STUDENT VALUES ('JONES','EDWARD','EAJ5073', 6);
INSERT INTO STUDENT VALUES ('KALMAR','PETER','PJK5220', 3);
INSERT INTO STUDENT VALUES ('KARSH','JAMES','JRK5377', 12);
INSERT INTO STUDENT VALUES ('KELLEHER','AUSTIN','ALK5492', 7);
INSERT INTO STUDENT VALUES ('KRUZAN','ANDREW','ASK5264', 4);
INSERT INTO STUDENT VALUES ('KUBACKI','DAVID','DMK5048', 5);
INSERT INTO STUDENT VALUES ('LIN','GARY','GQL5141', 6);
INSERT INTO STUDENT VALUES ('LOUCHART','GREGORY','GDL5051', 2);
INSERT INTO STUDENT VALUES ('OROSZ','ZACHARY','ZJO5002', 6);
INSERT INTO STUDENT VALUES ('PANETTA','MATTHEW','MDP5280', 9);
INSERT INTO STUDENT VALUES ('POLJAK','DYLAN','DJP5319', 4);
INSERT INTO STUDENT VALUES ('RAUSCH','AUSTIN','AHR5067', 12);
INSERT INTO STUDENT VALUES ('REESE','ARIN','AWR5319', 11);
INSERT INTO STUDENT VALUES ('REOTT','ZACHARY','ZDR5023', 6);
INSERT INTO STUDENT VALUES ('RISTAU','BRIAN','BJR5336', 2);
INSERT INTO STUDENT VALUES ('RISTAU','STEVEN','SPR5122', 2);
INSERT INTO STUDENT VALUES ('ROSSWOG','CHRISTOPHER','CMR5556', 10);
INSERT INTO STUDENT VALUES ('SHULTZ','JAMES','JTS5507', 8);
INSERT INTO STUDENT VALUES ('SITTERLEY','SHAUN','SMS6179', 4);
INSERT INTO STUDENT VALUES ('STANKIEWICZ','MARK','MIS5708', 9);
INSERT INTO STUDENT VALUES ('STEEN','JOSHUA','JDS5782', 9);
INSERT INTO STUDENT VALUES ('TAROSKY','KIMBERLY','KRT5110', 1);
INSERT INTO STUDENT VALUES ('TAYLOR','DYLAN','DMT5235', 3);
INSERT INTO STUDENT VALUES ('VALLO','ALEXANDER','ANV5067', 2);
INSERT INTO STUDENT VALUES ('WILCZEK','CONNOR','CVW5203', 5);